# Generated by Django 4.2.5 on 2023-09-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da empresa', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
    ]
