# Generated by Django 4.2.5 on 2023-09-27 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresas',
            new_name='Empresa',
        ),
    ]
