# Generated by Django 4.2.5 on 2023-09-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarHoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colaboradores.colaborador')),
            ],
            options={
                'verbose_name_plural': 'RegistrarHorasExtras',
                'ordering': ['colaborador'],
            },
        ),
    ]
