# Generated by Django 4.2.5 on 2023-09-27 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroHoraExtra',
            new_name='RegistrarHoraExtra',
        ),
    ]
